repos:
  - repo: local
    hooks:
      - id: lint
        name: Lint using Selene
        entry: selene
        language: system
        types:
          - lua
      - id: format
        name: Check formatting using StyLua
        entry: stylua --check
        language: system
        types:
          - lua