[package]
name = "thattimothy/shutdown"
version = "0.0.1-alpha"
description = "The easiest way to shutdown your game without worry."
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["src", "src/**", "LICENSE.md", "default.project.json", "wally.toml"]

[dependencies]
